#!/bin/bash
# build.sh - Bundle src/ source files into a single distributable n8n-host.sh
# Usage: bash build.sh

set -euo pipefail

DIST_DIR="dist"
OUT="${DIST_DIR}/n8n-host.sh"
SOURCES=(
  "src/lib/globals.sh"
  "src/lib/utils.sh"
  "src/lib/setup.sh"
  "src/lib/features/install.sh"
  "src/lib/features/domain.sh"
  "src/lib/features/upgrade.sh"
  "src/lib/features/auth.sh"
  "src/lib/features/data.sh"
  "src/lib/features/redis.sh"
  "src/lib/features/database.sh"
  "src/lib/features/service.sh"
  "src/lib/features/cleanup.sh"
  "src/lib/features/backup.sh"
  "src/lib/features/config.sh"
  "src/main.sh"
)

echo "[*] Building ${OUT}..."

mkdir -p "${DIST_DIR}"

# Write shebang + header
{
  echo "#!/bin/bash"
  echo ""
  echo "# n8n-host.sh - N8N Cloud Manager"
  echo "# Generated by build.sh — DO NOT EDIT DIRECTLY"
  echo "# Edit source files in src/ then run: bash build.sh"
  echo ""
} > "$OUT"

# Concatenate each source file (skip shebang if present)
for src in "${SOURCES[@]}"; do
  if [ ! -f "$src" ]; then
    echo "[!] Missing source file: $src"
    exit 1
  fi
  echo "# ---- ${src} ----" >> "$OUT"
  # Skip first line if it's a shebang
  if head -n1 "$src" | grep -q '^#!'; then
    tail -n +2 "$src" >> "$OUT"
  else
    cat "$src" >> "$OUT"
  fi
  echo "" >> "$OUT"
done

chmod +x "$OUT"
echo "[+] Built: ${OUT} ($(wc -l < "$OUT") lines)"
